services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 7777:5432
    environment:
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=12345678
      - POSTGRS_DB=library
    volumes:
      - ./postgres-data:/var/lib/postgresql/data