// generated by `sqlx migrate build-script`
use std::process::Command;
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    println!("cargo:rerun-if-changed=postgres-data");
    let _ = Command::new("cargo")
        .arg("sqlx")
        .arg("migrate")
        .arg("run")
        .spawn()
        .expect("Failed to spawn!");
}